# see: https://terraform-docs.io/user-guide/configuration/output/
output:
  file: README.md
  mode: inject

# see: https://terraform-docs.io/user-guide/configuration/formatter
formatter: markdown table

# see: https://terraform-docs.io/user-guide/configuration/sections/
sections:
  show:
    - inputs
    - outputs
    - resources
    - requirements
