# Code generated by scripts/update-pricing.sh. DO NOT EDIT manually.
#
# Public Scalingo rates for the osc-fr1 region, fetched from the Scalingo API
# on 2026-07-11. Prices are in EUR per month (30 days), VAT excluded.
# Use the `pricing` variable to override them (e.g. negotiated rates, other
# region).
#
# NOTE: initial partial seed — the addon plan list will be completed by the
# first run of the "Update pricing" workflow (workflow_dispatch or monthly
# schedule).
locals {
  default_pricing = {
    container_sizes = {
      "S"   = 7.2
      "M"   = 14.4
      "L"   = 28.8
      "XL"  = 57.6
      "2XL" = 115.2
    }
    addon_plans = {
      "postgresql-sandbox"      = 0
      "postgresql-starter-512"  = 7.2
      "postgresql-starter-1024" = 14.4
    }
  }
}
