#!/usr/bin/env bash
# Regenerates pricing_defaults.tf with the public Scalingo rates, fetched from
# the Scalingo API (these endpoints do not require authentication):
#   - GET /v1/container_sizes  -> monthly price of each container size
#   - GET /v1/addon_providers  -> monthly price of each addon plan
#
# Usage: scripts/update-pricing.sh [region]    (default: osc-fr1)
#
# This script is run monthly by the .github/workflows/update-pricing.yml
# workflow, which opens a pull request when the rates have changed.
set -euo pipefail

REGION="${1:-osc-fr1}"
API_BASE_URL="https://api.${REGION}.scalingo.com/v1"
OUTPUT_FILE="$(cd "$(dirname "$0")/.." && pwd)/pricing_defaults.tf"

# thirtydays_price is expressed in cents.
container_sizes="$(curl -fsSL "${API_BASE_URL}/container_sizes" | jq -r '
  .container_sizes
  | sort_by(.ordinal)[]
  | select(.thirtydays_price != null)
  | "      \"\(.name)\" = \(.thirtydays_price / 100)"
')"

# plan price is expressed in euros per month.
addon_plans="$(curl -fsSL "${API_BASE_URL}/addon_providers" | jq -r '
  [.addon_providers[].plans[]]
  | sort_by(.name)[]
  | select(.price != null)
  | "      \"\(.name)\" = \(.price)"
')"

if [ -z "${container_sizes}" ] || [ -z "${addon_plans}" ]; then
  echo "error: got an empty rate list from the Scalingo API, aborting" >&2
  exit 1
fi

cat > "${OUTPUT_FILE}" <<EOF
# Code generated by scripts/update-pricing.sh. DO NOT EDIT manually.
#
# Public Scalingo rates for the ${REGION} region, fetched from the Scalingo API
# on $(date -u +%Y-%m-%d). Prices are in EUR per month (30 days), VAT excluded.
# Use the \`pricing\` variable to override them (e.g. negotiated rates, other
# region).
locals {
  default_pricing = {
    container_sizes = {
${container_sizes}
    }
    addon_plans = {
${addon_plans}
    }
  }
}
EOF

if command -v terraform >/dev/null; then
  terraform fmt "${OUTPUT_FILE}" >/dev/null
fi

echo "wrote ${OUTPUT_FILE}"
